/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EcoCoin__factory } from "./EcoCoin__factory";
export { VerificationOracle__factory } from "./VerificationOracle__factory";
