"""Model Fidelity Badges — official / simplified / experimental."""
FM:dict[str,dict[str,str]]={}
def r(i,f,n=""):FM[i]={"fidelity":f,"note":n}
r("richards","simplified","FEM/FDM + van Genuchten")
r("penman_monteith","official","FAO-56 standard")
r("saint_venant","simplified","Dynamic/diffusive wave")
r("scs_cn","simplified","USDA SCS empirical")
r("daycent","simplified","7-pool C; no official API")
r("nitrogen_cycle","simplified","Monod kinetics")
r("soil_chemistry","simplified","Gapon/Vanselow")
r("rothc","official","Rothamsted 5-pool formulas")
r("aquacrop","official","aquacrop library Apache 2.0")
r("crop_yield","simplified","RUE+GDD; APSIM/DSSAT")
r("gdd_phenology","simplified","GDD method")
r("sebs","simplified","Energy balance literature")
r("ndvi_canopy","simplified","NDVI→LAI empirical")
r("starfm","experimental","Spatial-temporal fusion")
r("pinn","experimental","Physics-Informed NN")
r("lstm_hydrology","experimental","LSTM rainfall-runoff")
r("qaoa","experimental","Quantum QUBO")
r("simulated_annealing","simplified","Classical SA solver")
r("enkf","simplified","Ensemble Kalman Filter")
r("vm0042","official","Verra VM0042 v2.2")
r("shuttleworth_wallace","simplified","Dual-source ET")
def all()->dict:return dict(FM)
def badge(sid:str)->dict:return FM.get(sid,{"fidelity":"simplified","note":"Unregistered"})
