/**
 * ============================================================================
 *  Satellite Registry — 15+ free satellite data sources
 * ============================================================================
 */


import type { Satellite } from "./types";
import type { SatelliteRegistry, SatelliteIndex } from "./types";

export const SATELLITES: SatelliteRegistry = [
  {
    id: "sentinel-1",
    name: "Sentinel-1",
    agency: "ESA",
    launchYear: 2014,
    resolution: "5-20 m (SAR)",
    revisitDays: 6,
    swath: "250 km",
    access: "free",
    dataSource: "https://scihub.copernicus.eu",
    descriptionKey: "satellites.sentinel1.desc",
    icon: "🛰️",
    bands: [
      { name: "VV", wavelength: "5.4 GHz (C-band)", resolution: "5 m", application: "Soil moisture, flood mapping" },
      { name: "VH", wavelength: "5.4 GHz (C-band)", resolution: "20 m", application: "Vegetation structure" },
    ],
    applications: ["soil-moisture", "flood", "deforestation", "ice-monitoring"],
  },
  {
    id: "sentinel-2",
    name: "Sentinel-2",
    agency: "ESA",
    launchYear: 2015,
    resolution: "10 m",
    revisitDays: 5,
    swath: "290 km",
    access: "free",
    dataSource: "https://scihub.copernicus.eu",
    descriptionKey: "satellites.sentinel2.desc",
    icon: "🛰️",
    bands: [
      { name: "B2 (Blue)", wavelength: "490 nm", resolution: "10 m", application: "True color" },
      { name: "B3 (Green)", wavelength: "560 nm", resolution: "10 m", application: "NDWI" },
      { name: "B4 (Red)", wavelength: "665 nm", resolution: "10 m", application: "NDVI" },
      { name: "B8 (NIR)", wavelength: "842 nm", resolution: "10 m", application: "Vegetation" },
      { name: "B11 (SWIR)", wavelength: "1610 nm", resolution: "20 m", application: "NBR, NDMI" },
    ],
    applications: ["ndvi", "agriculture", "land-cover", "forest-monitoring"],
  },
  {
    id: "sentinel-3",
    name: "Sentinel-3",
    agency: "ESA",
    launchYear: 2016,
    resolution: "300 m",
    revisitDays: 1,
    swath: "1270 km",
    access: "free",
    dataSource: "https://scihub.copernicus.eu",
    descriptionKey: "satellites.sentinel3.desc",
    icon: "🛰️",
    bands: [
      { name: "Sea surface temp", wavelength: "10-12 μm", resolution: "1 km", application: "Ocean monitoring" },
      { name: "Land surface temp", wavelength: "10-12 μm", resolution: "1 km", application: "Fire detection" },
    ],
    applications: ["ocean", "fire", "temperature", "climate"],
  },
  {
    id: "sentinel-5p",
    name: "Sentinel-5P",
    agency: "ESA",
    launchYear: 2017,
    resolution: "7×3.5 km",
    revisitDays: 1,
    swath: "2600 km",
    access: "free",
    dataSource: "https://scihub.copernicus.eu",
    descriptionKey: "satellites.sentinel5p.desc",
    icon: "🛰️",
    bands: [
      { name: "NO2", wavelength: "UV-Vis", resolution: "7 km", application: "Air quality" },
      { name: "CO", wavelength: "SWIR", resolution: "7 km", application: "Air pollution" },
      { name: "O3", wavelength: "UV", resolution: "28 km", application: "Ozone layer" },
      { name: "SO2", wavelength: "UV", resolution: "7 km", application: "Volcanic activity" },
    ],
    applications: ["air-quality", "pollution", "ozone", "climate"],
  },
  {
    id: "landsat-8",
    name: "Landsat 8",
    agency: "NASA/USGS",
    launchYear: 2013,
    resolution: "30 m",
    revisitDays: 16,
    swath: "185 km",
    access: "free",
    dataSource: "https://earthexplorer.usgs.gov",
    descriptionKey: "satellites.landsat8.desc",
    icon: "🛰️",
    bands: [
      { name: "Coastal", wavelength: "433-453 nm", resolution: "30 m", application: "Water" },
      { name: "NIR", wavelength: "851-879 nm", resolution: "30 m", application: "Vegetation" },
      { name: "SWIR1", wavelength: "1566-1651 nm", resolution: "30 m", application: "Moisture" },
      { name: "TIRS", wavelength: "10-12 μm", resolution: "100 m", application: "Temperature" },
    ],
    applications: ["ndvi", "land-cover", "time-series", "agriculture"],
  },
  {
    id: "landsat-9",
    name: "Landsat 9",
    agency: "NASA/USGS",
    launchYear: 2021,
    resolution: "30 m",
    revisitDays: 16,
    swath: "185 km",
    access: "free",
    dataSource: "https://earthexplorer.usgs.gov",
    descriptionKey: "satellites.landsat9.desc",
    icon: "🛰️",
    bands: [
      { name: "NIR", wavelength: "851-879 nm", resolution: "30 m", application: "Vegetation" },
      { name: "SWIR1", wavelength: "1566-1651 nm", resolution: "30 m", application: "Moisture" },
    ],
    applications: ["ndvi", "land-cover", "time-series"],
  },
  {
    id: "modis",
    name: "MODIS (Terra/Aqua)",
    agency: "NASA",
    launchYear: 1999,
    resolution: "250 m - 1 km",
    revisitDays: 1,
    swath: "2330 km",
    access: "free",
    dataSource: "https://earthdata.nasa.gov",
    descriptionKey: "satellites.modis.desc",
    icon: "🛰️",
    bands: [
      { name: "Red", wavelength: "620-670 nm", resolution: "250 m", application: "Land cover" },
      { name: "Thermal", wavelength: "10-12 μm", resolution: "1 km", application: "Fire detection" },
    ],
    applications: ["fire", "snow", "evapotranspiration", "phenology"],
  },
  {
    id: "viirs",
    name: "VIIRS (Suomi NPP)",
    agency: "NASA/NOAA",
    launchYear: 2011,
    resolution: "375 m",
    revisitDays: 1,
    swath: "3000 km",
    access: "free",
    dataSource: "https://earthdata.nasa.gov",
    descriptionKey: "satellites.viirs.desc",
    icon: "🛰️",
    bands: [
      { name: "Day/Night Band", wavelength: "500-900 nm", resolution: "750 m", application: "Night lights" },
      { name: "Thermal", wavelength: "10-12 μm", resolution: "375 m", application: "Fire detection" },
    ],
    applications: ["fire", "night-lights", "urbanization"],
  },
  {
    id: "gpm",
    name: "GPM IMERG",
    agency: "NASA/JAXA",
    launchYear: 2014,
    resolution: "0.1° (~10 km)",
    revisitDays: 0,
    swath: "Global",
    access: "free",
    dataSource: "https://gpm.nasa.gov/data",
    descriptionKey: "satellites.gpm.desc",
    icon: "🌧️",
    bands: [
      { name: "Precipitation", wavelength: "Multi-frequency", resolution: "10 km", application: "Rainfall" },
    ],
    applications: ["precipitation", "flood", "drought", "hydrology"],
  },
  {
    id: "smap",
    name: "SMAP",
    agency: "NASA",
    launchYear: 2015,
    resolution: "9 km",
    revisitDays: 3,
    swath: "1000 km",
    access: "free",
    dataSource: "https://earthdata.nasa.gov",
    descriptionKey: "satellites.smap.desc",
    icon: "💧",
    bands: [
      { name: "L-band radar", wavelength: "1.26 GHz", resolution: "9 km", application: "Soil moisture" },
    ],
    applications: ["soil-moisture", "agriculture", "drought"],
  },
  {
    id: "grace-fo",
    name: "GRACE-FO",
    agency: "NASA/GFZ",
    launchYear: 2018,
    resolution: "~150 km",
    revisitDays: 30,
    swath: "Global",
    access: "free",
    dataSource: "https://earthdata.nasa.gov",
    descriptionKey: "satellites.grace.desc",
    icon: "🌊",
    bands: [
      { name: "Gravity anomaly", wavelength: "K-band ranging", resolution: "150 km", application: "Groundwater" },
    ],
    applications: ["groundwater", "ice-mass", "drought"],
  },
  {
    id: "icesat-2",
    name: "ICESat-2",
    agency: "NASA",
    launchYear: 2018,
    resolution: "~17 m",
    revisitDays: 91,
    swath: "Laser tracks",
    access: "free",
    dataSource: "https://earthdata.nasa.gov",
    descriptionKey: "satellites.icesat2.desc",
    icon: "❄️",
    bands: [
      { name: "ATLAS laser", wavelength: "532 nm", resolution: "17 m", application: "Ice elevation" },
    ],
    applications: ["ice", "forest-height", "bathymetry"],
  },
  {
    id: "gedi",
    name: "GEDI (ISS)",
    agency: "NASA",
    launchYear: 2018,
    resolution: "25 m",
    revisitDays: 0,
    swath: "4.2 km tracks",
    access: "free",
    dataSource: "https://earthdata.nasa.gov",
    descriptionKey: "satellites.gedi.desc",
    icon: "🌳",
    bands: [
      { name: "LiDAR", wavelength: "1064 nm", resolution: "25 m", application: "Forest canopy height" },
    ],
    applications: ["forest-height", "biomass", "carbon"],
  },
  {
    id: "chirps",
    name: "CHIRPS",
    agency: "UCSB",
    launchYear: 2015,
    resolution: "5 km",
    revisitDays: 1,
    swath: "Global (50°S-50°N)",
    access: "free",
    dataSource: "https://www.chc.ucsb.edu/data/chirps",
    descriptionKey: "satellites.chirps.desc",
    icon: "🌧️",
    bands: [
      { name: "Rainfall", wavelength: "Satellite+stations", resolution: "5 km", application: "Precipitation" },
    ],
    applications: ["precipitation", "agriculture", "drought"],
  },
  {
    id: "ecostress",
    name: "ECOSTRESS (ISS)",
    agency: "NASA",
    launchYear: 2018,
    resolution: "70 m",
    revisitDays: 0,
    swath: "384 km",
    access: "free",
    dataSource: "https://earthdata.nasa.gov",
    descriptionKey: "satellites.ecostress.desc",
    icon: "🌡️",
    bands: [
      { name: "Thermal IR", wavelength: "8-12 μm", resolution: "70 m", application: "Plant temperature" },
    ],
    applications: ["water-stress", "agriculture", "urban-heat"],
  },
];

export const SATELLITE_INDICES: readonly SatelliteIndex[] = [
  { id: "ndvi", formula: "(NIR - RED) / (NIR + RED)", name: "NDVI", application: "Vegetation health" },
  { id: "ndwi", formula: "(GREEN - NIR) / (GREEN + NIR)", name: "NDWI", application: "Water bodies" },
  { id: "ndmi", formula: "(NIR - SWIR) / (NIR + SWIR)", name: "NDMI", application: "Moisture content" },
  { id: "nbr", formula: "(NIR - SWIR2) / (NIR + SWIR2)", name: "NBR", application: "Burn severity" },
  { id: "evi", formula: "2.5 × (NIR - RED) / (NIR + 6×RED - 7.5×BLUE + 1)", name: "EVI", application: "Enhanced vegetation" },
  { id: "savi", formula: "((NIR - RED) / (NIR + RED + L)) × (1 + L)", name: "SAVI", application: "Sparse vegetation" },
  { id: "ndsi", formula: "(GREEN - SWIR) / (GREEN + SWIR)", name: "NDSI", application: "Snow cover" },
];

export function getSatelliteById(id: string): Satellite | undefined {
  return SATELLITES.find((s) => s.id === id);
}
