/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace VerificationOracle {
  export type ProjectStruct = {
    id: BigNumberish;
    name: string;
    region: string;
    ipfsHash: string;
    creditType: BigNumberish;
    startDate: BigNumberish;
    endDate: BigNumberish;
    verified: boolean;
  };

  export type ProjectStructOutput = [
    id: bigint,
    name: string,
    region: string,
    ipfsHash: string,
    creditType: bigint,
    startDate: bigint,
    endDate: bigint,
    verified: boolean
  ] & {
    id: bigint;
    name: string;
    region: string;
    ipfsHash: string;
    creditType: bigint;
    startDate: bigint;
    endDate: bigint;
    verified: boolean;
  };

  export type VerificationStruct = {
    verifier: AddressLike;
    timestamp: BigNumberish;
    dataHash: BytesLike;
    value: BigNumberish;
    valid: boolean;
  };

  export type VerificationStructOutput = [
    verifier: string,
    timestamp: bigint,
    dataHash: string,
    value: bigint,
    valid: boolean
  ] & {
    verifier: string;
    timestamp: bigint;
    dataHash: string;
    value: bigint;
    valid: boolean;
  };
}

export interface VerificationOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addVerifier"
      | "calculateCredits"
      | "getProject"
      | "getVerifications"
      | "projectCount"
      | "projectVerified"
      | "projects"
      | "registerProject"
      | "removeVerifier"
      | "steward"
      | "verifications"
      | "verifiers"
      | "verify"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ProjectRegistered"
      | "Verified"
      | "VerifierAdded"
      | "VerifierRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateCredits",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProject",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerifications",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "projectCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "projectVerified",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "projects",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProject",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "steward", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifications",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateCredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProject", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVerifications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "projects", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "steward", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifiers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace ProjectRegisteredEvent {
  export type InputTuple = [
    id: BigNumberish,
    name: string,
    creditType: BigNumberish
  ];
  export type OutputTuple = [id: bigint, name: string, creditType: bigint];
  export interface OutputObject {
    id: bigint;
    name: string;
    creditType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifiedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    verifier: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    verifier: string,
    value: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    verifier: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierAddedEvent {
  export type InputTuple = [verifier: AddressLike];
  export type OutputTuple = [verifier: string];
  export interface OutputObject {
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierRemovedEvent {
  export type InputTuple = [verifier: AddressLike];
  export type OutputTuple = [verifier: string];
  export interface OutputObject {
    verifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VerificationOracle extends BaseContract {
  connect(runner?: ContractRunner | null): VerificationOracle;
  waitForDeployment(): Promise<this>;

  interface: VerificationOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addVerifier: TypedContractMethod<
    [verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  calculateCredits: TypedContractMethod<
    [arg0: BigNumberish, value: BigNumberish, arg2: BytesLike],
    [bigint],
    "view"
  >;

  getProject: TypedContractMethod<
    [projectId: BigNumberish],
    [VerificationOracle.ProjectStructOutput],
    "view"
  >;

  getVerifications: TypedContractMethod<
    [projectId: BigNumberish],
    [VerificationOracle.VerificationStructOutput[]],
    "view"
  >;

  projectCount: TypedContractMethod<[], [bigint], "view">;

  projectVerified: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  projects: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, bigint, boolean] & {
        id: bigint;
        name: string;
        region: string;
        ipfsHash: string;
        creditType: bigint;
        startDate: bigint;
        endDate: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;

  registerProject: TypedContractMethod<
    [name: string, region: string, ipfsHash: string, creditType: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  removeVerifier: TypedContractMethod<
    [verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  steward: TypedContractMethod<[], [string], "view">;

  verifications: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, string, bigint, boolean] & {
        verifier: string;
        timestamp: bigint;
        dataHash: string;
        value: bigint;
        valid: boolean;
      }
    ],
    "view"
  >;

  verifiers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  verify: TypedContractMethod<
    [projectId: BigNumberish, value: BigNumberish, dataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addVerifier"
  ): TypedContractMethod<[verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "calculateCredits"
  ): TypedContractMethod<
    [arg0: BigNumberish, value: BigNumberish, arg2: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProject"
  ): TypedContractMethod<
    [projectId: BigNumberish],
    [VerificationOracle.ProjectStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVerifications"
  ): TypedContractMethod<
    [projectId: BigNumberish],
    [VerificationOracle.VerificationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "projectCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "projectVerified"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "projects"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, bigint, boolean] & {
        id: bigint;
        name: string;
        region: string;
        ipfsHash: string;
        creditType: bigint;
        startDate: bigint;
        endDate: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerProject"
  ): TypedContractMethod<
    [name: string, region: string, ipfsHash: string, creditType: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeVerifier"
  ): TypedContractMethod<[verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "steward"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifications"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, string, bigint, boolean] & {
        verifier: string;
        timestamp: bigint;
        dataHash: string;
        value: bigint;
        valid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifiers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [projectId: BigNumberish, value: BigNumberish, dataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ProjectRegistered"
  ): TypedContractEvent<
    ProjectRegisteredEvent.InputTuple,
    ProjectRegisteredEvent.OutputTuple,
    ProjectRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "Verified"
  ): TypedContractEvent<
    VerifiedEvent.InputTuple,
    VerifiedEvent.OutputTuple,
    VerifiedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierAdded"
  ): TypedContractEvent<
    VerifierAddedEvent.InputTuple,
    VerifierAddedEvent.OutputTuple,
    VerifierAddedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierRemoved"
  ): TypedContractEvent<
    VerifierRemovedEvent.InputTuple,
    VerifierRemovedEvent.OutputTuple,
    VerifierRemovedEvent.OutputObject
  >;

  filters: {
    "ProjectRegistered(uint256,string,uint256)": TypedContractEvent<
      ProjectRegisteredEvent.InputTuple,
      ProjectRegisteredEvent.OutputTuple,
      ProjectRegisteredEvent.OutputObject
    >;
    ProjectRegistered: TypedContractEvent<
      ProjectRegisteredEvent.InputTuple,
      ProjectRegisteredEvent.OutputTuple,
      ProjectRegisteredEvent.OutputObject
    >;

    "Verified(uint256,address,uint256)": TypedContractEvent<
      VerifiedEvent.InputTuple,
      VerifiedEvent.OutputTuple,
      VerifiedEvent.OutputObject
    >;
    Verified: TypedContractEvent<
      VerifiedEvent.InputTuple,
      VerifiedEvent.OutputTuple,
      VerifiedEvent.OutputObject
    >;

    "VerifierAdded(address)": TypedContractEvent<
      VerifierAddedEvent.InputTuple,
      VerifierAddedEvent.OutputTuple,
      VerifierAddedEvent.OutputObject
    >;
    VerifierAdded: TypedContractEvent<
      VerifierAddedEvent.InputTuple,
      VerifierAddedEvent.OutputTuple,
      VerifierAddedEvent.OutputObject
    >;

    "VerifierRemoved(address)": TypedContractEvent<
      VerifierRemovedEvent.InputTuple,
      VerifierRemovedEvent.OutputTuple,
      VerifierRemovedEvent.OutputObject
    >;
    VerifierRemoved: TypedContractEvent<
      VerifierRemovedEvent.InputTuple,
      VerifierRemovedEvent.OutputTuple,
      VerifierRemovedEvent.OutputObject
    >;
  };
}
