"""Free / low-friction EO & GIS sources with explicit operational roles.

Note: Many "free" services still require registration for production quotas.
Synthetic providers always work offline for local development.
"""

from __future__ import annotations

from typing import Any

# Role taxonomy used across API & UI
ROLES = {
    "vegetation": "Canopy vigor / NDVI–EVI proxies",
    "thermal": "Land surface temperature / heat stress",
    "topography": "Elevation, slope, aspect, DEM",
    "optical": "True-color / multispectral context",
    "radar": "Structure, moisture, all-weather",
    "precipitation": "Rain estimates for water balance",
    "gis_basemap": "Reference layers for farm maps",
    "soil": "Soil moisture / properties proxies",
}

SATELLITE_CATALOG: list[dict[str, Any]] = [
    {
        "id": "sentinel2_optical",
        "name": "Sentinel-2 MSI",
        "agency": "ESA Copernicus",
        "roles": ["vegetation", "optical"],
        "bands_hint": "B2/B3/B4/B8 → NDVI",
        "revisit_days": 5,
        "resolution_m": 10,
        "license": "open (Copernicus)",
        "auth": "optional_for_bulk",
        "provider_impl": "synthetic",  # swap to planetary/copernicus when keys exist
        "free_no_key_dev": True,
        "notes": "Primary vegetation index source when STAC/GEE wired",
    },
    {
        "id": "landsat8_9",
        "name": "Landsat 8/9 OLI-TIRS",
        "agency": "USGS/NASA",
        "roles": ["vegetation", "thermal", "optical"],
        "bands_hint": "OLI + TIRS LST",
        "revisit_days": 16,
        "resolution_m": 30,
        "license": "public domain",
        "auth": "optional",
        "provider_impl": "synthetic",
        "free_no_key_dev": True,
        "notes": "Thermal + optical long archive",
    },
    {
        "id": "modis_terra_aqua",
        "name": "MODIS Terra/Aqua",
        "agency": "NASA",
        "roles": ["vegetation", "thermal"],
        "bands_hint": "MOD13 / MOD11",
        "revisit_days": 1,
        "resolution_m": 250,
        "license": "public",
        "auth": "none_for_gibs_tiles",
        "provider_impl": "nasa_gibs",
        "free_no_key_dev": True,
        "notes": "Daily coarse NDVI/LST via GIBS WMS (no key)",
    },
    {
        "id": "viirs_npp",
        "name": "VIIRS (Suomi NPP / NOAA-20)",
        "agency": "NOAA/NASA",
        "roles": ["vegetation", "thermal"],
        "bands_hint": "VNP13 / LST",
        "revisit_days": 1,
        "resolution_m": 375,
        "license": "public",
        "auth": "none_for_gibs",
        "provider_impl": "nasa_gibs",
        "free_no_key_dev": True,
        "notes": "Night lights + vegetation continuity",
    },
    {
        "id": "sentinel1_sar",
        "name": "Sentinel-1 SAR",
        "agency": "ESA",
        "roles": ["radar", "soil"],
        "bands_hint": "VV/VH backscatter",
        "revisit_days": 6,
        "resolution_m": 10,
        "license": "open",
        "auth": "optional",
        "provider_impl": "synthetic",
        "free_no_key_dev": True,
        "notes": "All-weather structure / flood / soil moisture proxy",
    },
    {
        "id": "srtm_dem",
        "name": "SRTM 30m DEM",
        "agency": "NASA/NGA",
        "roles": ["topography"],
        "bands_hint": "elevation",
        "revisit_days": None,
        "resolution_m": 30,
        "license": "public",
        "auth": "none",
        "provider_impl": "opentopodata",
        "free_no_key_dev": True,
        "notes": "Elevation via OpenTopoData (no key)",
    },
    {
        "id": "aster_gdem",
        "name": "ASTER GDEM",
        "agency": "METI/NASA",
        "roles": ["topography"],
        "bands_hint": "elevation",
        "revisit_days": None,
        "resolution_m": 30,
        "license": "open with attribution",
        "auth": "none",
        "provider_impl": "opentopodata",
        "free_no_key_dev": True,
        "notes": "Alternate DEM where SRTM voids",
    },
    {
        "id": "open_elevation",
        "name": "Open-Elevation / OpenTopoData",
        "agency": "community",
        "roles": ["topography"],
        "bands_hint": "point elevation",
        "revisit_days": None,
        "resolution_m": 30,
        "license": "varies",
        "auth": "none",
        "provider_impl": "opentopodata",
        "free_no_key_dev": True,
        "notes": "HTTP elevation lookup without API key",
    },
    {
        "id": "nasa_power",
        "name": "NASA POWER",
        "agency": "NASA",
        "roles": ["precipitation", "thermal"],
        "bands_hint": "meteo / radiation",
        "revisit_days": 1,
        "resolution_m": 50000,
        "license": "public",
        "auth": "none",
        "provider_impl": "nasa_power",
        "free_no_key_dev": True,
        "notes": "Agromet time series free REST",
    },
    {
        "id": "open_meteo",
        "name": "Open-Meteo",
        "agency": "community",
        "roles": ["precipitation", "thermal"],
        "bands_hint": "forecast + historical",
        "revisit_days": 1,
        "resolution_m": 9000,
        "license": "CC / free non-commercial tiers",
        "auth": "none",
        "provider_impl": "open_meteo",
        "free_no_key_dev": True,
        "notes": "No-key weather & soil moisture models",
    },
    {
        "id": "osm_basemap",
        "name": "OpenStreetMap",
        "agency": "OSMF",
        "roles": ["gis_basemap"],
        "bands_hint": "vector basemap",
        "revisit_days": None,
        "resolution_m": None,
        "license": "ODbL",
        "auth": "none",
        "provider_impl": "osm",
        "free_no_key_dev": True,
        "notes": "Field context, roads, hydro lines",
    },
    {
        "id": "gibs_wmts",
        "name": "NASA GIBS WMTS",
        "agency": "NASA",
        "roles": ["optical", "vegetation", "thermal"],
        "bands_hint": "browse tiles",
        "revisit_days": 1,
        "resolution_m": 250,
        "license": "public",
        "auth": "none",
        "provider_impl": "nasa_gibs",
        "free_no_key_dev": True,
        "notes": "Slippy-map imagery without API key",
    },
]


def catalog_by_role(role: str | None = None) -> list[dict[str, Any]]:
    if not role:
        return SATELLITE_CATALOG
    return [s for s in SATELLITE_CATALOG if role in s.get("roles", [])]
