"""add_users_auth_simulation_ai_agents

Revision ID: f97ba62a8f79
Revises: 0001_admin_models
Create Date: 2026-07-24 01:26:11.247104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f97ba62a8f79'
down_revision: Union[str, None] = '0001_admin_models'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'total_publications')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'role')
    op.drop_column('users', 'h_index')
    op.drop_column('users', 'profile_image_url')
    op.drop_column('users', 'affiliation')
    op.drop_column('users', 'orcid_id')
    op.drop_column('users', 'total_citations')
    op.drop_column('users', 'research_interests')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=100), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('research_interests', sqlite.JSON(), nullable=True))
    op.add_column('users', sa.Column('total_citations', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('orcid_id', sa.VARCHAR(length=50), nullable=True))
    op.add_column('users', sa.Column('affiliation', sa.VARCHAR(length=300), nullable=True))
    op.add_column('users', sa.Column('profile_image_url', sa.VARCHAR(length=500), nullable=True))
    op.add_column('users', sa.Column('h_index', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=10), nullable=True))
    op.add_column('users', sa.Column('bio', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('total_publications', sa.INTEGER(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###
