"""add_all_remaining_tables

Revision ID: fc66f4570c5b
Revises: f97ba62a8f79
Create Date: 2026-07-24 01:35:14.927822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc66f4570c5b'
down_revision: Union[str, None] = 'f97ba62a8f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
