port 1194
proto udp
dev tun
sndbuf 0
rcvbuf 0
persist-key
persist-tun
keepalive 10 120
tls-server
cipher AES-256-CBC
auth SHA256
user nobody
group nogroup
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 1.1.1.1"
push "dhcp-option DNS 1.0.0.1"
client-to-client
duplicate-cn
status openvpn-status.log
log-append /var/log/openvpn.log
verb 3
