@echo off
REM Economugin API Server Launcher
REM Generated by magic_api_launcher.py
cd /d D:\econojin.com
call .venv\Scripts\activate.bat
echo.
echo 🚀 Starting Economugin API Server...
echo 📚 Docs will be available at: http://127.0.0.1:8000/docs
echo.
python -m uvicorn scripts.api.main:app --host 0.0.0.0 --port 8000 --reload
pause
