[pytest]
testpaths = apps/api/tests
asyncio_default_fixture_loop_scope = function
asyncio_mode = auto
filterwarnings = ignore::pytest.PytestCollectionWarning
# غیرفعال‌سازی افزونه‌های مزاحم web3
addopts = -p no:web3.tools
