/** 45+ lightweight hub pages for product surface coverage (Phase 6–8 frontend). */
export type HubRoute = { slug: string; title: string; titleFa: string; blurb: string };

export const HUB_ROUTES: HubRoute[] = [
  { slug: "water-balance", title: "Water balance", titleFa: "بیلان آب", blurb: "DSS water balance indicators" },
  { slug: "irrigation-scheduler", title: "Irrigation scheduler", titleFa: "زمان‌بندی آبیاری", blurb: "Threshold and interval planning" },
  { slug: "soil-health", title: "Soil health", titleFa: "سلامت خاک", blurb: "SOC and structure overview" },
  { slug: "carbon-farming", title: "Carbon farming", titleFa: "کشاورزی کربن", blurb: "Residue and RothC narratives" },
  { slug: "ndvi-lab", title: "NDVI lab", titleFa: "آزمایشگاه NDVI", blurb: "Free EO indices" },
  { slug: "lai-canopy", title: "LAI / canopy", titleFa: "LAI و تاج پوشش", blurb: "Canopy from NDVI" },
  { slug: "pest-risk", title: "Pest risk", titleFa: "ریسک آفت", blurb: "Seasonal risk flags" },
  { slug: "disease-watch", title: "Disease watch", titleFa: "پایش بیماری", blurb: "Humidity-linked alerts" },
  { slug: "fertilizer-plan", title: "Fertilizer plan", titleFa: "برنامه کود", blurb: "N-P-K planning stub" },
  { slug: "seed-catalog", title: "Seed catalog", titleFa: "کاتالوگ بذر", blurb: "Inventory link" },
  { slug: "market-prices", title: "Market prices", titleFa: "قیمت بازار", blurb: "Local price notes" },
  { slug: "cooperative", title: "Cooperative", titleFa: "تعاونی", blurb: "Community co-op tools" },
  { slug: "extension", title: "Extension services", titleFa: "ترویج کشاورزی", blurb: "Advisor workflows" },
  { slug: "youth-academy", title: "Youth academy", titleFa: "آکادمی جوانان", blurb: "Education tracks" },
  { slug: "women-farmers", title: "Women farmers", titleFa: "کشاورزان زن", blurb: "Inclusive programs" },
  { slug: "climate-adaptation", title: "Climate adaptation", titleFa: "سازگاری اقلیمی", blurb: "Scenario stress tests" },
  { slug: "drought-early-warning", title: "Drought early warning", titleFa: "هشدار خشکسالی", blurb: "SPI-style stubs" },
  { slug: "flood-risk", title: "Flood risk", titleFa: "ریسک سیل", blurb: "Runoff SCS notes" },
  { slug: "groundwater", title: "Groundwater", titleFa: "آب زیرزمینی", blurb: "Abstraction tracking" },
  { slug: "watershed", title: "Watershed", titleFa: "حوضه آبریز", blurb: "SWAT-proxy link" },
  { slug: "biodiversity", title: "Biodiversity", titleFa: "تنوع زیستی", blurb: "Habitat indicators" },
  { slug: "agroforestry", title: "Agroforestry", titleFa: "زراعت جنگلی", blurb: "Tree–crop systems" },
  { slug: "pasture", title: "Pasture", titleFa: "مرتع", blurb: "Grazing pressure" },
  { slug: "livestock-health", title: "Livestock health", titleFa: "سلامت دام", blurb: "Herd notes" },
  { slug: "cold-chain", title: "Cold chain", titleFa: "زنجیره سرد", blurb: "Post-harvest loss" },
  { slug: "warehouse", title: "Warehouse", titleFa: "انبار", blurb: "Stock levels" },
  { slug: "traceability", title: "Traceability", titleFa: "ردیابی", blurb: "Batch ledger" },
  { slug: "certification", title: "Certification", titleFa: "گواهی", blurb: "Organic / GAP stubs" },
  { slug: "insurance", title: "Crop insurance", titleFa: "بیمه محصول", blurb: "Index insurance notes" },
  { slug: "credit-scoring", title: "Credit scoring", titleFa: "رتبه‌بندی اعتباری", blurb: "Farm risk score" },
  { slug: "npv-lab", title: "NPV lab", titleFa: "آزمایشگاه NPV", blurb: "Economics module" },
  { slug: "irr-lab", title: "IRR lab", titleFa: "آزمایشگاه IRR", blurb: "Project returns" },
  { slug: "break-even", title: "Break-even", titleFa: "نقطه سربه‌سر", blurb: "Cost–volume" },
  { slug: "grant-finder", title: "Grant finder", titleFa: "یافتن کمک‌هزینه", blurb: "Funding catalog" },
  { slug: "policy-brief", title: "Policy brief", titleFa: "خلاصه سیاستی", blurb: "Exportable notes" },
  { slug: "open-data", title: "Open data", titleFa: "داده باز", blurb: "Public datasets" },
  { slug: "api-status", title: "API status", titleFa: "وضعیت API", blurb: "Health mirror" },
  { slug: "deploy-guide", title: "Deploy guide", titleFa: "راهنمای استقرار", blurb: "Free tier steps" },
  { slug: "security-checklist", title: "Security checklist", titleFa: "چک‌لیست امنیت", blurb: "Phase 4 gates" },
  { slug: "bandit-report", title: "Bandit report", titleFa: "گزارش Bandit", blurb: "SAST summary" },
  { slug: "research-lab", title: "Research lab", titleFa: "آزمایشگاه پژوهش", blurb: "Phase 8 track" },
  { slug: "pilot-iran", title: "Pilot Iran", titleFa: "پایلوت ایران", blurb: "Isfahan wheat" },
  { slug: "pilot-afghanistan", title: "Pilot Afghanistan", titleFa: "پایلوت افغانستان", blurb: "Regional template" },
  { slug: "pilot-iraq", title: "Pilot Iraq", titleFa: "پایلوت عراق", blurb: "Regional template" },
  { slug: "offline-mode", title: "Offline mode", titleFa: "حالت آفلاین", blurb: "PWA notes" },
  { slug: "pwa-install", title: "PWA install", titleFa: "نصب PWA", blurb: "Add to home screen" },
  { slug: "i18n-center", title: "i18n center", titleFa: "مرکز چندزبانه", blurb: "Locale coverage" },
  { slug: "accessibility", title: "Accessibility", titleFa: "دسترسی‌پذیری", blurb: "A11y checklist" },
  { slug: "changelog", title: "Changelog", titleFa: "تغییرات", blurb: "Release notes" },
  { slug: "roadmap", title: "Roadmap", titleFa: "نقشه راه", blurb: "Phases 1–8" },
];
