"""EO, climate, soil & GIS sources with explicit operational roles.

Many free services work without API keys for low-volume / development use.
Synthetic providers always work offline.
"""

from __future__ import annotations

from typing import Any

# Role taxonomy — used across API, UI filters, and provider routing
ROLES: dict[str, str] = {
    # original core
    "vegetation": "Canopy vigor / NDVI–EVI / phenology",
    "thermal": "Land surface temperature / heat stress",
    "topography": "Elevation, slope, aspect, DEM, drainage",
    "optical": "True-color / multispectral visual context",
    "radar": "SAR structure, flood, all-weather backscatter",
    "precipitation": "Rain / snowfall estimates for water balance",
    "gis_basemap": "Reference vector/raster basemaps for farm maps",
    "soil": "Soil class, texture, organic matter proxies",
    # expanded (≥20 additional operational roles)
    "soil_moisture": "Surface/root-zone soil water content (m³/m³ or %)",
    "evapotranspiration": "ET0 / ETc / water demand for irrigation",
    "humidity": "Air relative humidity / vapor pressure deficit",
    "wind": "Wind speed/direction for spray drift & ET",
    "solar_radiation": "Shortwave radiation / PAR for growth models",
    "snow": "Snow cover / SWE for mountain & winter water",
    "flood": "Inundation / water extent mapping",
    "drought": "Drought indices (SPI/SPEI/NDWI stress)",
    "fire": "Active fire / burned area",
    "land_cover": "Crop type / land-use classification",
    "biomass": "Above-ground biomass / yield proxies",
    "chlorophyll": "Leaf chlorophyll / nitrogen stress",
    "water_quality": "Turbidity, chlorophyll-a in water bodies",
    "groundwater": "Groundwater storage / GRACE-class anomalies",
    "air_quality": "Aerosols / dust / PM affecting crops",
    "cloud": "Cloud mask / optical availability",
    "night_lights": "VIIRS night lights / infrastructure context",
    "carbon": "SOC / flux proxies for MRV & RothC inputs",
    "pest_habitat": "Humidity–temp suitability layers for IPM",
    "irrigation_proxy": "Irrigated area / canopy water stress",
    "erosion_risk": "RUSLE factors from rain + slope + cover",
    "salinity": "Soil/water salinity stress indicators",
    "phenology": "Green-up / senescence timing",
    "yield": "Yield estimation / forecast layers",
    "hydrography": "Rivers, canals, reservoirs geometry",
    "boundaries": "Admin / parcel / cadastral boundaries",
    "weather_forecast": "Short-range meteo forecast grids",
    "climate_normal": "Long-term climate normals",
}

SATELLITE_CATALOG: list[dict[str, Any]] = [
    # —— Optical / vegetation ——
    {
        "id": "sentinel2_optical",
        "name": "Sentinel-2 MSI",
        "agency": "ESA Copernicus",
        "roles": ["vegetation", "optical", "chlorophyll", "phenology", "land_cover"],
        "bands_hint": "B2/B3/B4/B8 → NDVI; B5–B7 red-edge",
        "revisit_days": 5,
        "resolution_m": 10,
        "license": "open (Copernicus)",
        "auth": "optional_for_bulk",
        "provider_impl": "synthetic",
        "free_no_key_dev": True,
        "notes": "Primary field-scale vegetation source",
    },
    {
        "id": "landsat8_9",
        "name": "Landsat 8/9 OLI-TIRS",
        "agency": "USGS/NASA",
        "roles": ["vegetation", "thermal", "optical", "land_cover"],
        "bands_hint": "OLI + TIRS LST",
        "revisit_days": 16,
        "resolution_m": 30,
        "license": "public domain",
        "auth": "optional",
        "provider_impl": "synthetic",
        "free_no_key_dev": True,
        "notes": "Long archive + thermal",
    },
    {
        "id": "modis_terra_aqua",
        "name": "MODIS Terra/Aqua",
        "agency": "NASA",
        "roles": ["vegetation", "thermal", "fire", "snow", "phenology"],
        "bands_hint": "MOD13 NDVI, MOD11 LST, MOD14 fire",
        "revisit_days": 1,
        "resolution_m": 250,
        "license": "public",
        "auth": "none_for_gibs_tiles",
        "provider_impl": "nasa_gibs",
        "free_no_key_dev": True,
        "notes": "Daily coarse vegetation & LST",
    },
    {
        "id": "viirs_npp",
        "name": "VIIRS (Suomi NPP / NOAA-20)",
        "agency": "NOAA/NASA",
        "roles": ["vegetation", "thermal", "night_lights", "fire"],
        "bands_hint": "VNP13, LST, DNB",
        "revisit_days": 1,
        "resolution_m": 375,
        "license": "public",
        "auth": "none_for_gibs",
        "provider_impl": "nasa_gibs",
        "free_no_key_dev": True,
        "notes": "Night lights + vegetation continuity",
    },
    # —— Radar / soil moisture structure ——
    {
        "id": "sentinel1_sar",
        "name": "Sentinel-1 SAR",
        "agency": "ESA",
        "roles": ["radar", "soil_moisture", "flood", "irrigation_proxy"],
        "bands_hint": "VV/VH backscatter",
        "revisit_days": 6,
        "resolution_m": 10,
        "license": "open",
        "auth": "optional",
        "provider_impl": "synthetic",
        "free_no_key_dev": True,
        "notes": "All-weather moisture & flood extent",
    },
    {
        "id": "smap_l3",
        "name": "SMAP L3 Soil Moisture",
        "agency": "NASA",
        "roles": ["soil_moisture", "drought"],
        "bands_hint": "surface & root-zone SM",
        "revisit_days": 2,
        "resolution_m": 9000,
        "license": "public",
        "auth": "none",
        "provider_impl": "synthetic",
        "free_no_key_dev": True,
        "notes": "Dedicated soil moisture mission product",
    },
    {
        "id": "ascat_soil",
        "name": "Metop ASCAT Soil Moisture",
        "agency": "EUMETSAT",
        "roles": ["soil_moisture", "drought"],
        "bands_hint": "scatterometer SM index",
        "revisit_days": 1,
        "resolution_m": 12500,
        "license": "open",
        "auth": "none",
        "provider_impl": "synthetic",
        "free_no_key_dev": True,
        "notes": "Operational EU soil moisture",
    },
    {
        "id": "grace_fo",
        "name": "GRACE-FO",
        "agency": "NASA/GFZ",
        "roles": ["groundwater", "drought"],
        "bands_hint": "terrestrial water storage anomaly",
        "revisit_days": 30,
        "resolution_m": 300000,
        "license": "public",
        "auth": "none",
        "provider_impl": "synthetic",
        "free_no_key_dev": True,
        "notes": "Basin-scale groundwater proxy",
    },
    # —— Topography ——
    {
        "id": "srtm_dem",
        "name": "SRTM 30m DEM",
        "agency": "NASA/NGA",
        "roles": ["topography", "erosion_risk", "hydrography"],
        "bands_hint": "elevation",
        "revisit_days": None,
        "resolution_m": 30,
        "license": "public",
        "auth": "none",
        "provider_impl": "opentopodata",
        "free_no_key_dev": True,
        "notes": "Elevation via OpenTopoData (no key)",
    },
    {
        "id": "aster_gdem",
        "name": "ASTER GDEM",
        "agency": "METI/NASA",
        "roles": ["topography"],
        "bands_hint": "elevation",
        "revisit_days": None,
        "resolution_m": 30,
        "license": "open with attribution",
        "auth": "none",
        "provider_impl": "opentopodata",
        "free_no_key_dev": True,
        "notes": "Alternate DEM where SRTM voids",
    },
    {
        "id": "open_elevation",
        "name": "Open-Elevation / OpenTopoData",
        "agency": "community",
        "roles": ["topography"],
        "bands_hint": "point elevation",
        "revisit_days": None,
        "resolution_m": 30,
        "license": "varies",
        "auth": "none",
        "provider_impl": "opentopodata",
        "free_no_key_dev": True,
        "notes": "HTTP elevation lookup without API key",
    },
    # —— Climate / meteo (no key) ——
    {
        "id": "nasa_power",
        "name": "NASA POWER",
        "agency": "NASA",
        "roles": [
            "precipitation",
            "thermal",
            "solar_radiation",
            "humidity",
            "wind",
            "evapotranspiration",
            "climate_normal",
        ],
        "bands_hint": "meteo / radiation / ag parameters",
        "revisit_days": 1,
        "resolution_m": 50000,
        "license": "public",
        "auth": "none",
        "provider_impl": "nasa_power",
        "free_no_key_dev": True,
        "notes": "Free agromet REST — ET0 inputs",
    },
    {
        "id": "open_meteo",
        "name": "Open-Meteo",
        "agency": "community",
        "roles": [
            "weather_forecast",
            "precipitation",
            "thermal",
            "humidity",
            "wind",
            "soil_moisture",
            "evapotranspiration",
            "solar_radiation",
        ],
        "bands_hint": "forecast + historical + soil layers",
        "revisit_days": 1,
        "resolution_m": 9000,
        "license": "CC / free tiers",
        "auth": "none",
        "provider_impl": "open_meteo",
        "free_no_key_dev": True,
        "notes": "No-key soil moisture 0–7cm / 7–28cm models",
    },
    {
        "id": "chirps_precip",
        "name": "CHIRPS Precipitation",
        "agency": "UCSB/CHG",
        "roles": ["precipitation", "drought"],
        "bands_hint": "daily/pentad rainfall",
        "revisit_days": 1,
        "resolution_m": 5500,
        "license": "public",
        "auth": "none",
        "provider_impl": "synthetic",
        "free_no_key_dev": True,
        "notes": "Preferred rainfall for drought SPI",
    },
    {
        "id": "gpm_imerg",
        "name": "GPM IMERG",
        "agency": "NASA",
        "roles": ["precipitation"],
        "bands_hint": "half-hourly rain",
        "revisit_days": 1,
        "resolution_m": 10000,
        "license": "public",
        "auth": "none",
        "provider_impl": "synthetic",
        "free_no_key_dev": True,
        "notes": "Global precipitation mission",
    },
    # —— Soil properties ——
    {
        "id": "soilgrids",
        "name": "SoilGrids 2.0",
        "agency": "ISRIC",
        "roles": ["soil", "carbon", "salinity", "erosion_risk"],
        "bands_hint": "texture, pH, SOC, bulk density",
        "revisit_days": None,
        "resolution_m": 250,
        "license": "CC-BY",
        "auth": "none",
        "provider_impl": "synthetic",
        "free_no_key_dev": True,
        "notes": "Global soil property maps — RothC inputs",
    },
    {
        "id": "hwsd",
        "name": "Harmonized World Soil Database",
        "agency": "FAO/IIASA",
        "roles": ["soil"],
        "bands_hint": "soil mapping units",
        "revisit_days": None,
        "resolution_m": 1000,
        "license": "open",
        "auth": "none",
        "provider_impl": "synthetic",
        "free_no_key_dev": True,
        "notes": "Legacy global soil types",
    },
    # —— Water / flood / quality ——
    {
        "id": "jrc_gsw",
        "name": "JRC Global Surface Water",
        "agency": "EC JRC",
        "roles": ["flood", "hydrography", "irrigation_proxy"],
        "bands_hint": "occurrence, seasonality, change",
        "revisit_days": None,
        "resolution_m": 30,
        "license": "open",
        "auth": "none",
        "provider_impl": "synthetic",
        "free_no_key_dev": True,
        "notes": "Long-term surface water & flood history",
    },
    {
        "id": "modis_flood",
        "name": "MODIS NRT Flood",
        "agency": "NASA",
        "roles": ["flood"],
        "bands_hint": "water detection",
        "revisit_days": 1,
        "resolution_m": 250,
        "license": "public",
        "auth": "none",
        "provider_impl": "nasa_gibs",
        "free_no_key_dev": True,
        "notes": "Near-real-time flood extents",
    },
    # —— Land cover / biomass / yield ——
    {
        "id": "esa_worldcover",
        "name": "ESA WorldCover",
        "agency": "ESA",
        "roles": ["land_cover", "biomass"],
        "bands_hint": "11-class map",
        "revisit_days": None,
        "resolution_m": 10,
        "license": "open",
        "auth": "none",
        "provider_impl": "synthetic",
        "free_no_key_dev": True,
        "notes": "Crop vs natural class context",
    },
    {
        "id": "modis_lai",
        "name": "MODIS LAI/FPAR",
        "agency": "NASA",
        "roles": ["biomass", "vegetation", "yield"],
        "bands_hint": "LAI, FPAR",
        "revisit_days": 4,
        "resolution_m": 500,
        "license": "public",
        "auth": "none",
        "provider_impl": "synthetic",
        "free_no_key_dev": True,
        "notes": "Canopy structure for yield models",
    },
    # —— Fire / air / cloud ——
    {
        "id": "firms_viirs",
        "name": "FIRMS VIIRS Active Fire",
        "agency": "NASA",
        "roles": ["fire"],
        "bands_hint": "hotspots",
        "revisit_days": 1,
        "resolution_m": 375,
        "license": "public",
        "auth": "none",
        "provider_impl": "nasa_gibs",
        "free_no_key_dev": True,
        "notes": "Crop residue burn & wildfire alerts",
    },
    {
        "id": "modis_aod",
        "name": "MODIS Aerosol Optical Depth",
        "agency": "NASA",
        "roles": ["air_quality", "cloud"],
        "bands_hint": "AOD",
        "revisit_days": 1,
        "resolution_m": 10000,
        "license": "public",
        "auth": "none",
        "provider_impl": "nasa_gibs",
        "free_no_key_dev": True,
        "notes": "Dust events affecting photosynthesis",
    },
    # —— GIS basemap / boundaries ——
    {
        "id": "osm_basemap",
        "name": "OpenStreetMap",
        "agency": "OSMF",
        "roles": ["gis_basemap", "hydrography", "boundaries"],
        "bands_hint": "vector basemap",
        "revisit_days": None,
        "resolution_m": None,
        "license": "ODbL",
        "auth": "none",
        "provider_impl": "osm",
        "free_no_key_dev": True,
        "notes": "Roads, canals, place names",
    },
    {
        "id": "gibs_wmts",
        "name": "NASA GIBS WMTS",
        "agency": "NASA",
        "roles": ["optical", "vegetation", "thermal", "gis_basemap"],
        "bands_hint": "browse tiles",
        "revisit_days": 1,
        "resolution_m": 250,
        "license": "public",
        "auth": "none",
        "provider_impl": "nasa_gibs",
        "free_no_key_dev": True,
        "notes": "Slippy-map imagery without API key",
    },
    {
        "id": "natural_earth",
        "name": "Natural Earth",
        "agency": "NACIS",
        "roles": ["boundaries", "gis_basemap"],
        "bands_hint": "admin vectors",
        "revisit_days": None,
        "resolution_m": None,
        "license": "public domain",
        "auth": "none",
        "provider_impl": "osm",
        "free_no_key_dev": True,
        "notes": "Country/province boundaries",
    },
    # —— Composite / derived agri intelligence ——
    {
        "id": "ndwi_surface",
        "name": "NDWI / NDMI composites",
        "agency": "derived",
        "roles": ["soil_moisture", "irrigation_proxy", "drought", "vegetation"],
        "bands_hint": "from Sentinel-2 / Landsat",
        "revisit_days": 5,
        "resolution_m": 10,
        "license": "derived",
        "auth": "none",
        "provider_impl": "synthetic",
        "free_no_key_dev": True,
        "notes": "Canopy water content & irrigation stress",
    },
    {
        "id": "spei_grid",
        "name": "SPEI / SPI drought grids",
        "agency": "derived",
        "roles": ["drought", "precipitation"],
        "bands_hint": "standardized precip-ET index",
        "revisit_days": 30,
        "resolution_m": 25000,
        "license": "derived",
        "auth": "none",
        "provider_impl": "synthetic",
        "free_no_key_dev": True,
        "notes": "Feeds risk engine drought score",
    },
    {
        "id": "pest_climate_suitability",
        "name": "Pest climate suitability",
        "agency": "derived",
        "roles": ["pest_habitat", "humidity", "thermal"],
        "bands_hint": "degree-day + RH surfaces",
        "revisit_days": 1,
        "resolution_m": 9000,
        "license": "derived",
        "auth": "none",
        "provider_impl": "synthetic",
        "free_no_key_dev": True,
        "notes": "IPM early warning layer",
    },
]


def catalog_by_role(role: str | None = None) -> list[dict[str, Any]]:
    if not role:
        return SATELLITE_CATALOG
    return [s for s in SATELLITE_CATALOG if role in s.get("roles", [])]


def roles_list() -> list[dict[str, str]]:
    return [{"code": k, "meaning": v} for k, v in ROLES.items()]
