# -*- coding: utf-8 -*-
"""
Configuration for Econojin API
"""

import os
from pathlib import Path

# Server Configuration
HOST =REDACTED_BY_TRIAGE_TOOL
PORT =REDACTED_BY_TRIAGE_TOOL
DEBUG =REDACTED_BY_TRIAGE_TOOL
RELOAD =REDACTED_BY_TRIAGE_TOOL

# Database Configuration
DATABASE_URL =REDACTED_BY_TRIAGE_TOOL

# Redis Configuration
REDIS_URL =REDACTED_BY_TRIAGE_TOOL

# API Configuration
API_V1_PREFIX =REDACTED_BY_TRIAGE_TOOL
PROJECT_NAME =REDACTED_BY_TRIAGE_TOOL
VERSION =REDACTED_BY_TRIAGE_TOOL
DESCRIPTION =REDACTED_BY_TRIAGE_TOOL

# CORS Configuration
CORS_ORIGINS =REDACTED_BY_TRIAGE_TOOL
    "http: REDACTED_BY_TRIAGE_TOOL
    "http: REDACTED_BY_TRIAGE_TOOL
    "http: REDACTED_BY_TRIAGE_TOOL
    "https: REDACTED_BY_TRIAGE_TOOL
    "https: REDACTED_BY_TRIAGE_TOOL
]

# JWT Configuration
SECRET_KEY =REDACTED_BY_TRIAGE_TOOL
ALGORITHM =REDACTED_BY_TRIAGE_TOOL
ACCESS_TOKEN_EXPIRE_MINUTES =REDACTED_BY_TRIAGE_TOOL

# Gaia Protocol Configuration
GAIA_CONTRACT_ADDRESS =REDACTED_BY_TRIAGE_TOOL
GAIA_ORACLE_PRIVATE_KEY =REDACTED_BY_TRIAGE_TOOL
POLYGON_RPC_URL =REDACTED_BY_TRIAGE_TOOL

# Copernicus/Sentinel-2 Configuration
COPERNICUS_CLIENT_ID =REDACTED_BY_TRIAGE_TOOL
COPERNICUS_CLIENT_SECRET =REDACTED_BY_TRIAGE_TOOL

# Paths
BASE_DIR =REDACTED_BY_TRIAGE_TOOL
DATA_DIR =REDACTED_BY_TRIAGE_TOOL
UPLOAD_DIR =REDACTED_BY_TRIAGE_TOOL

# Ensure directories exist
DATA_DIR.mkdir(exist_ok=REDACTED_BY_TRIAGE_TOOL
UPLOAD_DIR.mkdir(exist_ok=REDACTED_BY_TRIAGE_TOOL
