#!/usr/bin/env python3
"""
Enhanced Component Extraction & Integration Script
Extracts, renames, and integrates components from advanced GitHub projects:
Resolution: 2024/07/20 - v2.0
"""
import json
import os
import shutil
import subprocess
from pathlib import Path
from typing import Any

BASE_DIR = Path(__file__).parent.parent
REPOS_DIR = BASE_DIR / "repos"
WEB_SRC = BASE_DIR / "apps" / "web" / "src"

# Priority repos with their frontend assets
GITHUB_REPOS = {
    "shadcn-ui": {
        "url": "https://github.com/shadcn-ui/ui.git",
        "targets": ["packages/ui/src"],
        "rename": {"shadcn": "econojin", "ShadCN": "EcoNojin"},
    },
    "bulletproof-react": {
        "url": "https://github.com/alan2207/bulletproof-react.git",
        "targets": ["apps/web/src/features", "apps/web/src/lib"],
        "rename": {"bulletproof": "econojin", "Bulletproof": "EcoNojin"},
    },
    "tailadmin": {
        "url": "https://github.com/TailAdmin/nextjs-admin-template.git",
        "targets": ["apps/admin_panel/frontend/src"],
        "rename": {"tailadmin": "econojin", "TailAdmin": "EcoNojin"},
    },
    "claude-agent-monitor": {
        "url": "https://github.com/RL-CLM/claude-agent-monitor.git",
        "targets": ["apps/ai_agents/frontend/src"],
        "rename": {"claude": "econojin", "Claude": "EcoNojin"},
    },
}


def clone_repo(name: str, config: dict) -> Path:
    """Clone repo with shallow depth."""
    repo_url = config["url"]
    repo_path = REPOS_DIR / name
    if repo_path.exists():
        print(f"[SKIP] {name} already exists.")
        return repo_path
    print(f"[CLONE] {name} -> {repo_path}")
    if not REPOS_DIR.exists():
        REPOS_DIR.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["git", "clone", "--depth", "1", repo_url, str(repo_path)],
        check=True,
        capture_output=True,
    )
    return repo_path


def rename_in_content(content: str, mappings: dict[str, str]) -> str:
    """Replace names in text content."""
    for old, new in mappings.items():
        content = content.replace(old, new)
    return content


def add_attribution(content: str, source: str) -> str:
    """Add attribution comment to file."""
    header = (
        f"// Auto-generated by extract_github_components.py\n"
        f"// Source: {source}\n"
        f"// Attribution: Extracted from {source} under its original license.\n\n"
    )
    if content.startswith("//"):
        return content
    return header + content


def integrate_component(src: Path, dest: Path, source_label: str, rename_map: dict) -> None:
    """Copy and transform a single component file."""
    if not src.exists() or not src.is_file():
        return
    try:
        content = src.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        print(f"[WARN] Skipping binary file: {src}")
        return
    content = rename_in_content(content, rename_map)
    content = add_attribution(content, source_label)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(content, encoding="utf-8")
    print(f"  [INTEGRATE] {src.name} -> {dest}")


def integrate_repo(name: str, config: dict) -> None:
    """Integrate a repo into workspace based on config."""
    repo_path = REPOS_DIR / name
    if not repo_path.exists():
        print(f"[WARN] Repo {name} not found, skipping integration.")
        return

    source_label = config["url"].replace("https://github.com/", "").replace(".git", "")
    print(f"\n[INTEGRATE] {name} from {source_label}")

    # Map repo files to workspace destinations
    for target_rel in config["targets"]:
        target_dir = BASE_DIR / target_rel
        if not target_dir.exists():
            print(f"  [SKIP] Target directory does not exist: {target_rel}")
            continue
        repo_files = list(repo_path.rglob("*"))
        for src_path in repo_files:
            if not src_path.is_file():
                continue
            rel = src_path.relative_to(repo_path)
            suffix = src_path.suffix.lower()
            if suffix not in {".tsx", ".ts", ".jsx", ".js", ".css", ".json"}:
                continue
            dest = target_dir / rel
            integrate_component(src_path, dest, source_label, config["rename"])


def generate_integration_report() -> None:
    """Generate summary JSON of integrated repos and files."""
    report: dict[str, Any] = {"repositories": {}}
    for name in GITHUB_REPOS:
        repo_path = REPOS_DIR / name
        if not repo_path.exists():
            continue
        files = [
            str(p.relative_to(repo_path))
            for p in repo_path.rglob("*")
            if p.is_file() and p.suffix.lower() in {".tsx", ".ts", ".jsx", ".js", ".css", ".json"}
        ]
        report["repositories"][name] = {"files_count": len(files), "files": files[:50]}
    out = REPOS_DIR / "integration_report.json"
    out.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\n[REPORT] Saved to {out}")


def main() -> None:
    print("=== Phase4: GitHub Component Extraction ===\n")
    for name, config in GITHUB_REPOS.items():
        clone_repo(name, config)
    for name, config in GITHUB_REPOS.items():
        integrate_repo(name, config)
    generate_integration_report()
    print("\n[COMPLETE] Component extraction and integration finished.")


if __name__ == "__main__":
    main()