"""Default agronomy templates by category."""

from __future__ import annotations

CATEGORY_DEFAULTS: dict[str, dict] = {
    "cereal": {
        "planting_method": "drilling",
        "row_spacing_cm": 15,
        "sowing_depth_cm": 3,
        "irrigation_method": "sprinkler",
        "irrigation_interval_days": 10,
        "kc_mid": 1.15,
        "fertilizer_n_kg_ha": 120,
        "fertilizer_p_kg_ha": 40,
        "fertilizer_k_kg_ha": 40,
        "soil_ph_min": 6.0,
        "soil_ph_max": 7.5,
        "harvest_method": "combine",
        "harvest_moisture_pct": 14,
        "common_pests": "Aphids; Sunn pest; Armyworm",
        "common_diseases": "Rust; Powdery mildew; Fusarium",
        "care_notes": "Monitor tillering; avoid late N; weed early",
    },
    "legume": {
        "planting_method": "drilling",
        "row_spacing_cm": 30,
        "sowing_depth_cm": 4,
        "irrigation_method": "drip",
        "irrigation_interval_days": 8,
        "kc_mid": 1.05,
        "fertilizer_n_kg_ha": 20,
        "fertilizer_p_kg_ha": 50,
        "fertilizer_k_kg_ha": 40,
        "soil_ph_min": 6.0,
        "soil_ph_max": 7.5,
        "harvest_method": "combine",
        "common_pests": "Pod borer; Aphids",
        "common_diseases": "Ascochyta; Root rot",
        "care_notes": "Inoculate seed with rhizobia; avoid excess N",
    },
    "vegetable": {
        "planting_method": "transplant",
        "row_spacing_cm": 60,
        "plant_spacing_cm": 40,
        "sowing_depth_cm": 1.5,
        "irrigation_method": "drip",
        "irrigation_interval_days": 3,
        "kc_mid": 1.1,
        "fertilizer_n_kg_ha": 150,
        "fertilizer_p_kg_ha": 60,
        "fertilizer_k_kg_ha": 120,
        "soil_ph_min": 5.8,
        "soil_ph_max": 7.0,
        "harvest_method": "hand",
        "common_pests": "Whitefly; Tuta; Thrips",
        "common_diseases": "Blight; Powdery mildew; Virus",
        "care_notes": "Mulch; stake if needed; IPM traps",
    },
    "fruit": {
        "planting_method": "orchard planting",
        "row_spacing_cm": 400,
        "plant_spacing_cm": 300,
        "irrigation_method": "drip",
        "irrigation_interval_days": 5,
        "kc_mid": 0.9,
        "fertilizer_n_kg_ha": 100,
        "fertilizer_p_kg_ha": 40,
        "fertilizer_k_kg_ha": 120,
        "soil_ph_min": 6.0,
        "soil_ph_max": 7.5,
        "harvest_method": "hand",
        "common_pests": "Codling moth; Scale; Mites",
        "common_diseases": "Scab; Fire blight; Anthracnose",
        "care_notes": "Prune dormant; thin fruit; monitor soil moisture",
    },
    "forage": {
        "planting_method": "broadcast",
        "irrigation_method": "flood",
        "irrigation_interval_days": 12,
        "kc_mid": 1.2,
        "fertilizer_n_kg_ha": 80,
        "fertilizer_p_kg_ha": 40,
        "fertilizer_k_kg_ha": 60,
        "harvest_method": "mower",
        "common_pests": "Armyworm; Aphids",
        "common_diseases": "Leaf spot",
        "care_notes": "Cut at early bloom for quality",
    },
    "oilseed": {
        "planting_method": "drilling",
        "row_spacing_cm": 25,
        "irrigation_method": "sprinkler",
        "irrigation_interval_days": 9,
        "kc_mid": 1.1,
        "fertilizer_n_kg_ha": 100,
        "fertilizer_p_kg_ha": 40,
        "fertilizer_k_kg_ha": 40,
        "harvest_method": "combine",
        "common_pests": "Aphids; Flea beetle",
        "common_diseases": "Sclerotinia; Blackleg",
        "care_notes": "Avoid water stress at flowering",
    },
    "spice": {
        "planting_method": "corm/seed",
        "irrigation_method": "drip",
        "irrigation_interval_days": 14,
        "kc_mid": 0.7,
        "fertilizer_n_kg_ha": 50,
        "fertilizer_p_kg_ha": 30,
        "fertilizer_k_kg_ha": 40,
        "harvest_method": "hand",
        "common_pests": "Rodents; Thrips",
        "common_diseases": "Corm rot; Fusarium",
        "care_notes": "Light irrigation; careful post-harvest drying",
    },
    "herb": {
        "planting_method": "transplant/seed",
        "irrigation_method": "drip",
        "irrigation_interval_days": 4,
        "kc_mid": 0.95,
        "fertilizer_n_kg_ha": 60,
        "fertilizer_p_kg_ha": 30,
        "fertilizer_k_kg_ha": 50,
        "harvest_method": "hand",
        "common_pests": "Aphids; Whitefly",
        "common_diseases": "Damping-off; Rust",
        "care_notes": "Harvest before full flower for oils",
    },
    "industrial": {
        "planting_method": "drilling",
        "irrigation_method": "furrow",
        "irrigation_interval_days": 10,
        "kc_mid": 1.15,
        "fertilizer_n_kg_ha": 140,
        "fertilizer_p_kg_ha": 50,
        "fertilizer_k_kg_ha": 50,
        "harvest_method": "machine",
        "common_pests": "Bollworm; Aphids",
        "common_diseases": "Wilt; Leaf spot",
        "care_notes": "Follow IPM thresholds",
    },
    "nut": {
        "planting_method": "orchard planting",
        "irrigation_method": "drip",
        "irrigation_interval_days": 7,
        "kc_mid": 0.85,
        "fertilizer_n_kg_ha": 90,
        "fertilizer_p_kg_ha": 40,
        "fertilizer_k_kg_ha": 100,
        "harvest_method": "shake/hand",
        "common_pests": "Navel orangeworm; Mites",
        "common_diseases": "Anthracnose; Verticillium",
        "care_notes": "Deep infrequent irrigation for roots",
    },
}
