"""100+ crop catalog entries for seed."""

from __future__ import annotations

# name, name_fa, scientific, category, season, water_mm, days, description
RAW_CROPS: list[tuple] = [
    ("Wheat", "گندم", "Triticum aestivum", "cereal", "winter", 450, 150, "Staple temperate cereal"),
    ("Durum wheat", "گندم دوروم", "Triticum durum", "cereal", "winter", 420, 140, "Pasta-quality hard wheat"),
    ("Barley", "جو", "Hordeum vulgare", "cereal", "winter", 380, 120, "Feed and malt barley"),
    ("Oats", "یولاف", "Avena sativa", "cereal", "spring", 400, 110, "Cool-season cereal"),
    ("Rye", "چاودار", "Secale cereale", "cereal", "winter", 350, 130, "Cold-tolerant grain"),
    ("Triticale", "تریتیکاله", "× Triticosecale", "cereal", "winter", 400, 135, "Wheat-rye hybrid"),
    ("Corn", "ذرت", "Zea mays", "cereal", "summer", 550, 110, "Maize for grain or silage"),
    ("Sweet corn", "ذرت شیرین", "Zea mays saccharata", "cereal", "summer", 520, 85, "Fresh market maize"),
    ("Sorghum", "سورگوم", "Sorghum bicolor", "cereal", "summer", 400, 100, "Drought-tolerant grain"),
    ("Millet pearl", "ارزن مرواریدی", "Pennisetum glaucum", "cereal", "summer", 320, 90, "Dryland small grain"),
    ("Millet foxtail", "ارزن دم‌روباهی", "Setaria italica", "cereal", "summer", 300, 80, "Short-season millet"),
    ("Rice", "برنج", "Oryza sativa", "cereal", "summer", 1200, 130, "Paddy rice"),
    ("Quinoa", "کینوا", "Chenopodium quinoa", "cereal", "spring", 350, 120, "Andean pseudocereal"),
    ("Buckwheat", "گندم سیاه", "Fagopyrum esculentum", "cereal", "summer", 300, 75, "Fast cover crop grain"),
    ("Amaranth grain", "آمارانت دانه", "Amaranthus hypochondriacus", "cereal", "summer", 280, 90, "Pseudocereal"),
    ("Chickpea", "نخود", "Cicer arietinum", "legume", "spring", 350, 100, "Pulse crop"),
    ("Lentil", "عدس", "Lens culinaris", "legume", "spring", 280, 95, "Cool-season pulse"),
    ("Faba bean", "باقلا", "Vicia faba", "legume", "winter", 400, 140, "Broad bean"),
    ("Common bean", "لوبیا", "Phaseolus vulgaris", "legume", "summer", 400, 90, "Dry or snap bean"),
    ("Mung bean", "ماش", "Vigna radiata", "legume", "summer", 320, 70, "Short-cycle pulse"),
    ("Cowpea", "لوبیا چشم‌بلبلی", "Vigna unguiculata", "legume", "summer", 300, 80, "Heat-tolerant legume"),
    ("Soybean", "سویا", "Glycine max", "legume", "summer", 500, 120, "Oil and protein crop"),
    ("Pea", "نخود فرنگی", "Pisum sativum", "legume", "spring", 350, 90, "Garden or field pea"),
    ("Groundnut", "بادام‌زمینی", "Arachis hypogaea", "legume", "summer", 500, 130, "Peanut"),
    ("Alfalfa", "یونجه", "Medicago sativa", "forage", "perennial", 800, 365, "Perennial forage legume"),
    ("Clover red", "شبدر قرمز", "Trifolium pratense", "forage", "perennial", 600, 365, "Forage clover"),
    ("Clover white", "شبدر سفید", "Trifolium repens", "forage", "perennial", 550, 365, "Pasture clover"),
    ("Vetch common", "ماشک", "Vicia sativa", "forage", "winter", 350, 150, "Cover and forage"),
    ("Ryegrass", "چمن چاودار", "Lolium multiflorum", "forage", "winter", 500, 200, "Annual ryegrass"),
    ("Sudangrass", "سودان گراس", "Sorghum × drummondii", "forage", "summer", 450, 80, "Summer forage"),
    ("Tomato", "گوجه‌فرنگی", "Solanum lycopersicum", "vegetable", "summer", 600, 90, "Fresh and processing tomato"),
    ("Cherry tomato", "گوجه گیلاسی", "Solanum lycopersicum var.", "vegetable", "summer", 580, 75, "Small fruit tomato"),
    ("Cucumber", "خیار", "Cucumis sativus", "vegetable", "summer", 500, 60, "Fresh cucumber"),
    ("Watermelon", "هندوانه", "Citrullus lanatus", "vegetable", "summer", 550, 90, "Melon crop"),
    ("Melon", "خربزه", "Cucumis melo", "vegetable", "summer", 500, 85, "Cantaloupe / honeydew"),
    ("Pumpkin", "کدو تنبل", "Cucurbita pepo", "vegetable", "summer", 450, 100, "Winter squash type"),
    ("Zucchini", "کدو سبز", "Cucurbita pepo", "vegetable", "summer", 420, 50, "Summer squash"),
    ("Eggplant", "بادمجان", "Solanum melongena", "vegetable", "summer", 500, 100, "Aubergine"),
    ("Pepper bell", "فلفل دلمه‌ای", "Capsicum annuum", "vegetable", "summer", 480, 85, "Sweet pepper"),
    ("Chili pepper", "فلفل تند", "Capsicum annuum", "vegetable", "summer", 450, 90, "Hot pepper"),
    ("Onion", "پیاز", "Allium cepa", "vegetable", "winter", 400, 150, "Bulb onion"),
    ("Garlic", "سیر", "Allium sativum", "vegetable", "winter", 350, 180, "Clove crop"),
    ("Leek", "تره‌فرنگی", "Allium porrum", "vegetable", "winter", 380, 160, "Allium vegetable"),
    ("Potato", "سیب‌زمینی", "Solanum tuberosum", "vegetable", "spring", 500, 110, "Tuber crop"),
    ("Sweet potato", "سیب‌زمینی شیرین", "Ipomoea batatas", "vegetable", "summer", 450, 120, "Root crop"),
    ("Carrot", "هویج", "Daucus carota", "vegetable", "spring", 350, 90, "Root vegetable"),
    ("Radish", "تربچه", "Raphanus sativus", "vegetable", "spring", 250, 35, "Fast root crop"),
    ("Beet", "چغندر لبویی", "Beta vulgaris", "vegetable", "spring", 350, 70, "Table beet"),
    ("Sugar beet", "چغندرقند", "Beta vulgaris", "industrial", "spring", 550, 180, "Sugar industrial crop"),
    ("Cabbage", "کلم", "Brassica oleracea var. capitata", "vegetable", "winter", 400, 90, "Head cabbage"),
    ("Cauliflower", "گل‌کلم", "Brassica oleracea var. botrytis", "vegetable", "winter", 420, 95, "Brassica head"),
    ("Broccoli", "بروکلی", "Brassica oleracea var. italica", "vegetable", "winter", 400, 85, "Brassica florets"),
    ("Spinach", "اسفناج", "Spinacia oleracea", "vegetable", "winter", 300, 45, "Leafy green"),
    ("Lettuce", "کاهو", "Lactuca sativa", "vegetable", "spring", 280, 55, "Salad green"),
    ("Parsley", "جعفری", "Petroselinum crispum", "herb", "spring", 300, 80, "Culinary herb"),
    ("Coriander", "گشنیز", "Coriandrum sativum", "herb", "spring", 280, 50, "Leaf and seed herb"),
    ("Dill", "شوید", "Anethum graveolens", "herb", "spring", 260, 45, "Aromatic herb"),
    ("Basil", "ریحان", "Ocimum basilicum", "herb", "summer", 350, 60, "Warm-season herb"),
    ("Mint", "نعناع", "Mentha spicata", "herb", "perennial", 500, 365, "Perennial herb"),
    ("Thyme", "آویشن", "Thymus vulgaris", "herb", "perennial", 250, 365, "Mediterranean herb"),
    ("Rosemary", "رزماری", "Salvia rosmarinus", "herb", "perennial", 280, 365, "Woody herb"),
    ("Saffron", "زعفران", "Crocus sativus", "spice", "autumn", 300, 200, "High-value stigma spice"),
    ("Cumin", "زیره سبز", "Cuminum cyminum", "spice", "spring", 280, 110, "Seed spice"),
    ("Fennel", "رازیانه", "Foeniculum vulgare", "spice", "spring", 350, 120, "Seed and bulb"),
    ("Sesame", "کنجد", "Sesamum indicum", "oilseed", "summer", 350, 100, "Oilseed"),
    ("Sunflower", "آفتابگردان", "Helianthus annuus", "oilseed", "summer", 500, 110, "Oilseed sunflower"),
    ("Canola", "کلزا", "Brassica napus", "oilseed", "winter", 450, 160, "Rapeseed oil crop"),
    ("Safflower", "گلرنگ", "Carthamus tinctorius", "oilseed", "spring", 350, 120, "Drought oilseed"),
    ("Flax", "کتان", "Linum usitatissimum", "oilseed", "spring", 350, 100, "Linseed"),
    ("Cotton", "پنبه", "Gossypium hirsutum", "industrial", "summer", 700, 160, "Fiber crop"),
    ("Tobacco", "توتون", "Nicotiana tabacum", "industrial", "summer", 500, 120, "Leaf industrial"),
    ("Hemp industrial", "کنف صنعتی", "Cannabis sativa", "industrial", "summer", 450, 110, "Fiber/seed hemp"),
    ("Apple", "سیب", "Malus domestica", "fruit", "perennial", 700, 365, "Orchard tree"),
    ("Pear", "گلابی", "Pyrus communis", "fruit", "perennial", 650, 365, "Orchard tree"),
    ("Peach", "هلو", "Prunus persica", "fruit", "perennial", 700, 365, "Stone fruit"),
    ("Apricot", "زردآلو", "Prunus armeniaca", "fruit", "perennial", 600, 365, "Stone fruit"),
    ("Plum", "آلو", "Prunus domestica", "fruit", "perennial", 600, 365, "Stone fruit"),
    ("Cherry", "گیلاس", "Prunus avium", "fruit", "perennial", 650, 365, "Stone fruit"),
    ("Grape", "انگور", "Vitis vinifera", "fruit", "perennial", 500, 365, "Vine crop"),
    ("Pomegranate", "انار", "Punica granatum", "fruit", "perennial", 450, 365, "Mediterranean fruit"),
    ("Fig", "انجیر", "Ficus carica", "fruit", "perennial", 400, 365, "Subtropical fruit"),
    ("Date palm", "خرما", "Phoenix dactylifera", "fruit", "perennial", 900, 365, "Oasis fruit"),
    ("Olive", "زیتون", "Olea europaea", "fruit", "perennial", 400, 365, "Oil and table olive"),
    ("Citrus orange", "پرتقال", "Citrus sinensis", "fruit", "perennial", 800, 365, "Citrus orchard"),
    ("Citrus lemon", "لیمو", "Citrus limon", "fruit", "perennial", 750, 365, "Citrus"),
    ("Almond", "بادام", "Prunus dulcis", "nut", "perennial", 500, 365, "Tree nut"),
    ("Walnut", "گردو", "Juglans regia", "nut", "perennial", 700, 365, "Tree nut"),
    ("Pistachio", "پسته", "Pistacia vera", "nut", "perennial", 450, 365, "Dryland tree nut"),
    ("Hazelnut", "فندق", "Corylus avellana", "nut", "perennial", 600, 365, "Tree nut"),
    ("Strawberry", "توت‌فرنگی", "Fragaria × ananassa", "fruit", "spring", 500, 120, "Berry"),
    ("Raspberry", "تمشک", "Rubus idaeus", "fruit", "perennial", 550, 365, "Berry cane"),
    ("Blueberry", "بلوبری", "Vaccinium corymbosum", "fruit", "perennial", 600, 365, "Acid-soil berry"),
    ("Tea", "چای", "Camellia sinensis", "industrial", "perennial", 1200, 365, "Leaf beverage crop"),
    ("Coffee arabica", "قهوه", "Coffea arabica", "industrial", "perennial", 1400, 365, "Highland coffee"),
    ("Banana", "موز", "Musa acuminata", "fruit", "perennial", 1500, 365, "Tropical fruit"),
    ("Avocado", "آووکادو", "Persea americana", "fruit", "perennial", 900, 365, "Subtropical fruit"),
    ("Mango", "انبه", "Mangifera indica", "fruit", "perennial", 1000, 365, "Tropical fruit"),
    ("Guava", "گوآوا", "Psidium guajava", "fruit", "perennial", 800, 365, "Tropical fruit"),
    ("Papaya", "پاپایا", "Carica papaya", "fruit", "perennial", 1100, 365, "Tropical fruit"),
    ("Asparagus", "مارچوبه", "Asparagus officinalis", "vegetable", "perennial", 400, 365, "Perennial vegetable"),
    ("Artichoke", "کنگر فرنگی", "Cynara cardunculus", "vegetable", "perennial", 500, 365, "Mediterranean vegetable"),
    ("Okra", "بامیه", "Abelmoschus esculentus", "vegetable", "summer", 450, 70, "Warm vegetable"),
    ("Taro", "تارو", "Colocasia esculenta", "vegetable", "summer", 1200, 200, "Root tropical"),
    ("Cassava", "کاساوا", "Manihot esculenta", "vegetable", "perennial", 800, 300, "Tropical starch root"),
    ("Yam", "یام", "Dioscorea spp.", "vegetable", "summer", 900, 250, "Tropical tuber"),
    ("Mustard", "خردل", "Brassica juncea", "oilseed", "spring", 350, 90, "Oil and leaf mustard"),
    ("Kenaf", "کنف", "Hibiscus cannabinus", "industrial", "summer", 500, 120, "Fiber crop"),
    ("Jute", "جوت", "Corchorus olitorius", "industrial", "summer", 600, 120, "Bast fiber"),
    ("Lavender", "اسطوخودوس", "Lavandula angustifolia", "herb", "perennial", 300, 365, "Essential oil herb"),
    ("Chamomile", "بابونه", "Matricaria chamomilla", "herb", "spring", 280, 70, "Medicinal flower"),
    ("Aloe vera", "آلوئه‌ورا", "Aloe barbadensis", "industrial", "perennial", 250, 365, "Succulent industrial"),
    ("Stevia", "استویا", "Stevia rebaudiana", "industrial", "summer", 500, 120, "Natural sweetener leaf"),
    ("Hop", "هاپ", "Humulus lupulus", "industrial", "perennial", 600, 365, "Brewing cone crop"),
]

assert len(RAW_CROPS) >= 100, len(RAW_CROPS)
