from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings): REDACTED_BY_TRIAGE_TOOL
    model_config =REDACTED_BY_TRIAGE_TOOL

    APP_NAME: str =REDACTED_BY_TRIAGE_TOOL
    APP_VERSION: str =REDACTED_BY_TRIAGE_TOOL
    DEBUG: bool =REDACTED_BY_TRIAGE_TOOL
    HOST: str =REDACTED_BY_TRIAGE_TOOL
    PORT: int =REDACTED_BY_TRIAGE_TOOL
    DATABASE_URL: str =REDACTED_BY_TRIAGE_TOOL
    JWT_SECRET: str =REDACTED_BY_TRIAGE_TOOL
    JWT_ALGORITHM: str =REDACTED_BY_TRIAGE_TOOL
    JWT_EXPIRE_DAYS: int =REDACTED_BY_TRIAGE_TOOL
    ALLOWED_ORIGINS: list[str] =REDACTED_BY_TRIAGE_TOOL
        "http: REDACTED_BY_TRIAGE_TOOL
        "http: REDACTED_BY_TRIAGE_TOOL
        "http: REDACTED_BY_TRIAGE_TOOL
    ]
    RATE_LIMIT_ENABLED: bool =REDACTED_BY_TRIAGE_TOOL
    RATE_LIMIT_MAX_REQUESTS: int =REDACTED_BY_TRIAGE_TOOL
    RATE_LIMIT_WINDOW_SEC: int =REDACTED_BY_TRIAGE_TOOL
    REQUIRE_AUTH_FOR_WRITES: bool =REDACTED_BY_TRIAGE_TOOL
    OTP_DEV_MODE: bool =REDACTED_BY_TRIAGE_TOOL
    SMS_PROVIDER: str =REDACTED_BY_TRIAGE_TOOL
    KAVENEGAR_API_KEY: str =REDACTED_BY_TRIAGE_TOOL
    KAVENEGAR_TEMPLATE: str =REDACTED_BY_TRIAGE_TOOL
    TWILIO_ACCOUNT_SID: str =REDACTED_BY_TRIAGE_TOOL
    TWILIO_AUTH_TOKEN: str =REDACTED_BY_TRIAGE_TOOL
    TWILIO_FROM_NUMBER: str =REDACTED_BY_TRIAGE_TOOL
    LLM_ENABLED: bool =REDACTED_BY_TRIAGE_TOOL
    OPENAI_API_KEY: str =REDACTED_BY_TRIAGE_TOOL
    OPENAI_BASE_URL: str =REDACTED_BY_TRIAGE_TOOL
    LLM_MODEL: str =REDACTED_BY_TRIAGE_TOOL
    AZURE_OPENAI_ENDPOINT: str =REDACTED_BY_TRIAGE_TOOL
    AZURE_OPENAI_KEY: str =REDACTED_BY_TRIAGE_TOOL
    AZURE_OPENAI_DEPLOYMENT: str =REDACTED_BY_TRIAGE_TOOL
    AZURE_OPENAI_API_VERSION: str =REDACTED_BY_TRIAGE_TOOL


settings =REDACTED_BY_TRIAGE_TOOL
