/** Extra high-impact MENAP pilots (Hydroma leverage zones). */
export const MENAP_EXTRA = [
  {
    id: "lb-bekaa",
    code: "LB-BEK",
    nameFa: "بقاعه لبنان",
    nameEn: "Bekaa Valley",
    countryFa: "لبنان",
    countryEn: "Lebanon",
    regionFa: "بقاعه",
    climate: "mediterranean" as const,
    climateLabelFa: "مدیترانه‌ای",
    lat: 33.85,
    lon: 36.0,
    areaHaTarget: 1800,
    focusFa: "احیای کشاورزی پس از تنش، بهره‌وری آب، کشاورزی حفاظتی",
    focusEn: "Post-stress farm recovery, water productivity, CA",
    hpPackages: ["HP-05", "HP-06", "HP-07", "HP-12"],
    models: ["AquaCrop", "WEAP", "RothC"],
    standards: ["GSOC-MRV", "FAO CA", "LDN"],
    kpis: [
      { labelFa: "WP آب", target: "+20", unit: "%" },
      { labelFa: "اشتغال محلی", target: "0.4", unit: "job/ha" },
    ],
    phasePlan: ["آموزش FFS", "مالچ و CA", "MRV", "بازار محلی"],
    priority: 2 as const,
    icon: "🇱🇧",
  },
  {
    id: "sy-aleppo",
    code: "SY-ALP",
    nameFa: "حلب و حومه",
    nameEn: "Aleppo peri-urban",
    countryFa: "سوریه",
    countryEn: "Syria",
    regionFa: "شمال سوریه",
    climate: "semi_arid_plain" as const,
    climateLabelFa: "نیمه‌خشک",
    lat: 36.2,
    lon: 37.15,
    areaHaTarget: 2200,
    focusFa: "بازسازی معیشت، SWC مشارکتی، امنیت غذایی محلی",
    focusEn: "Livelihood rebuild, participatory SWC, local food security",
    hpPackages: ["HP-01", "HP-03", "HP-08", "HP-11", "HP-12"],
    models: ["RUSLE", "AquaCrop"],
    standards: ["FAO FFS", "WOCAT", "LDN"],
    kpis: [
      { labelFa: "کاهش فرسایش", target: "≥30", unit: "%" },
      { labelFa: "غذای محلی", target: "بهبود", unit: "index" },
    ],
    phasePlan: ["گروه محلی", "زای و بندک", "کارگاه", "پایش"],
    priority: 1 as const,
    icon: "🤝",
  },
  {
    id: "ye-sanaa",
    code: "YE-SAN",
    nameFa: "پیرامون صنعا / تراس‌های یمن",
    nameEn: "Sanaa terraces",
    countryFa: "یمن",
    countryEn: "Yemen",
    regionFa: "ارتفاعات یمن",
    climate: "arid_mountain" as const,
    climateLabelFa: "کوهستان خشک",
    lat: 15.35,
    lon: 44.2,
    areaHaTarget: 1500,
    focusFa: "تراس سنتی، کاهش رواناب، معیشت کوهستانی",
    focusEn: "Traditional terraces, runoff control, mountain livelihoods",
    hpPackages: ["HP-01", "HP-02", "HP-08", "HP-12"],
    models: ["RUSLE", "SWAT+"],
    standards: ["WOCAT terrace", "LDN"],
    kpis: [
      { labelFa: "کاهش رواناب", target: "≥25", unit: "%" },
      { labelFa: "پایداری تراس", target: "بازسازی", unit: "km" },
    ],
    phasePlan: ["نقشه تراس", "بندک", "FFS", "پایش"],
    priority: 1 as const,
    icon: "🏔️",
  },
  {
    id: "sd-gezira",
    code: "SD-GEZ",
    nameFa: "جزیره سودان",
    nameEn: "Gezira",
    countryFa: "سودان",
    countryEn: "Sudan",
    regionFa: "جزیره",
    climate: "savanna" as const,
    climateLabelFa: "ساوانا نیمه‌خشک",
    lat: 14.4,
    lon: 33.5,
    areaHaTarget: 4000,
    focusFa: "بهره‌وری آبیاری کانالی، شوری، کربن خاک",
    focusEn: "Canal irrigation efficiency, salinity, soil carbon",
    hpPackages: ["HP-05", "HP-06", "HP-07", "HP-12"],
    models: ["AquaCrop", "WEAP", "RothC"],
    standards: ["FAO irrigation", "GSOC-MRV"],
    kpis: [
      { labelFa: "کاهش تلفات آب کانال", target: "≥15", unit: "%" },
      { labelFa: "SOC", target: "+0.15", unit: "%/3yr" },
    ],
    phasePlan: ["بیلان آب", "مالچ", "MRV", "آموزش"],
    priority: 2 as const,
    icon: "🌾",
  },
  {
    id: "dz-constantine",
    code: "DZ-CON",
    nameFa: "قسنطینه / شرق الجزایر",
    nameEn: "Constantine east",
    countryFa: "الجزایر",
    countryEn: "Algeria",
    regionFa: "شرق الجزایر",
    climate: "mediterranean" as const,
    climateLabelFa: "مدیترانه‌ای نیمه‌خشک",
    lat: 36.35,
    lon: 6.6,
    areaHaTarget: 2000,
    focusFa: "فرسایش دیم، زیتون، حفاظت آب‌وخاک",
    focusEn: "Rainfed erosion, olive, SWC",
    hpPackages: ["HP-01", "HP-03", "HP-06", "HP-12"],
    models: ["RUSLE", "AquaCrop"],
    standards: ["WOCAT", "LDN", "GSOC-MRV"],
    kpis: [
      { labelFa: "کاهش فرسایش", target: "≥35", unit: "%" },
      { labelFa: "نفوذ باران", target: "+25", unit: "%" },
    ],
    phasePlan: ["زای/هلالی", "FFS", "پایش NDVI", "بازار"],
    priority: 2 as const,
    icon: "🫒",
  },
  {
    id: "ly-jefara",
    code: "LY-JEF",
    nameFa: "جفاره لیبی",
    nameEn: "Jefara plain",
    countryFa: "لیبی",
    countryEn: "Libya",
    regionFa: "شمال غرب",
    climate: "hyper_arid" as const,
    climateLabelFa: "فراخشک ساحلی",
    lat: 32.8,
    lon: 13.0,
    areaHaTarget: 2000,
    focusFa: "آب زیرزمینی ساحلی، تبخیر، کشاورزی کم‌مصرف",
    focusEn: "Coastal groundwater, evaporation control, low-use farming",
    hpPackages: ["HP-04", "HP-05", "HP-07", "HP-12"],
    models: ["WEAP", "AquaCrop"],
    standards: ["FAO water", "GSOC-MRV"],
    kpis: [
      { labelFa: "کاهش تبخیر", target: "≥20", unit: "%" },
      { labelFa: "پایداری برداشت آب زیرزمینی", target: "بهبود", unit: "m" },
    ],
    phasePlan: ["بیلان آب", "مالچ", "آموزش", "پایش"],
    priority: 2 as const,
    icon: "💧",
  },
  {
    id: "om-dhofar",
    code: "OM-DHO",
    nameFa: "ظفار عمان",
    nameEn: "Dhofar",
    countryFa: "عمان",
    countryEn: "Oman",
    regionFa: "ظفار",
    climate: "arid_mountain" as const,
    climateLabelFa: "خشک موسمی",
    lat: 17.0,
    lon: 54.1,
    areaHaTarget: 1200,
    focusFa: "مرتع موسمی، تغذیه با باران خریف، تنوع زیستی",
    focusEn: "Monsoon rangeland, khareef recharge, biodiversity",
    hpPackages: ["HP-07", "HP-08", "HP-10", "HP-12"],
    models: ["SWAT+", "MaxEnt-stub", "RothC"],
    standards: ["LDN", "FAO pastoral"],
    kpis: [
      { labelFa: "پوشش مرتع پس از خریف", target: "+20", unit: "%" },
      { labelFa: "تغذیه فصلی", target: "پایش", unit: "mm" },
    ],
    phasePlan: ["نقشه مرتع", "چرای چرخشی", "پایش NDVI", "اکوتوریسم"],
    priority: 3 as const,
    icon: "🌿",
  },
] as const;
